import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { MovieProvider } from '@/context/movieContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Search Movie TMDB',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<MovieProvider>
				<body className={`${inter.className} text-white flex flex-col min-h-screen`}>
					<header className='bg-[#0d253f] w-full'>
						<Navbar />
					</header>
					<main className='flex-1'>{children}</main>
					<footer className='bg-[#0d253f] w-full'>
						<Footer />
					</footer>
				</body>
			</MovieProvider>
		</html>
	);
}
